config/routes.rb
Rails.application.routes.draw do

  root 'albums#index'
  get 'albums' => 'albums#index'
  get 'albums/new' => 'albums#new'
  get 'albums/:id' => 'albums#show', as: :album
  post 'albums' => 'albums#create'

  get 'signup'  => 'users#new'
  resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

end

app/models/album.rb
class Album < ActiveRecord::Base

  has_many :photos
  
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :album
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

# prevents logged out users from access the index or show pages
  before_action :require_user, only: [:index, :show]

  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
    @photos = @album.photos
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

# makes the current_user method available to all views
  helper_method :current_user

# determines whether a user is logged in or out by checking whether there is a user in the
# database with a given session id.  If there is, this means the user is logged in and @current_user
# will store that user otherwise @current_user is nil.
  def current_user
    @current_user ||= User.find(session[:user_id]) if
    session[:user_id]
  end

# redirects all calls to the login page unless the user is logged in i.e. a current user
  def require_user
    redirect_to '/login' unless current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      flash[:danger] = 'Invalid email/password combination'
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      flash[:danger] = 'Invalid email/password combination'
      redirect_to '/signup'
    end
  end


  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<div class="albums">
  <div class="container">

    <div class="row">
      <% @albums.each do |album|%>
        <div class="item col-md-4">
          <div class="img-container">
            <%= image_tag album.image %>
          </div>
          <div class="album-info">
            <h2><%= album.title %></h2>
            <p><%= link_to "See Album", album_path(album) %></p>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/albums/show.html.erb
<div class="photos">
  <div class="container">

    <h1><%= @album.title %></h1>
    <div class="row">
      <% @photos.each do |photo|%>
        <div class="item col-md-4">
          <div class="img-container">
            <%= image_tag photo.image %>
          </div>
          <div class="photo-info">
            <p><%= photo.caption %></p>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,300' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                
            <a class="navbar-brand" href="/">AUTH</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <% if current_user %>
                    <li class="nav-item nav-link" aria-current="page"><%= current_user.email %></li>
                    <li class="nav-item nav-link" aria-current="page">
                    <%= link_to "Log out", logout_path, :method => :get %>
                    </li>
                <% else %>
                    <li class="nav-item nav-link" aria-current="page"><%= link_to "Login", 'login' %></li>
                    <li class="nav-item nav-link"><%= link_to "Signup", 'signup' %></li>
                <% end %>
                </ul>
            </div>
            </div>
        </nav>
    <%= yield %>

  </body>
</html>

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <h1>Sign up</h1>

    <%= form_for(@user) do |f| %>
      <div class="form-outline mb-4">
        <%= f.text_field :first_name, :placeholder => "First name" %>
      </div>
      <div class="form-outline mb-4">
        <%= f.text_field :last_name, :placeholder => "Last name" %>
      </div>
      <div class="form-outline mb-4">
        <%= f.email_field :email, :placeholder => "Email" %>
      </div>
      <div class="form-outline mb-4">
        <%= f.password_field :password, :placeholder => "Password" %>
      </div>
      <%= f.submit "Create an account", class: "btn-submit" %>
    <% end %>

  </div>
</div>